### ISSUE TITLE
Issue with fancyhdr beamer and RMD

### ISSUE THREAD

**Issue by AlinneVeiga** [pietvo/fancyhdr#4]
Hey

I create slides using Rmarkdown on RStudio. Things were going fine untill like one hour ago. Then I started getting some warnings and can't be able to solve.

Before 1hour and 30 minutes ago, this worked fine: 

---
title: "EST052 - AMOSTRAGEM"
subtitle: Aula 27 - PPT
author: "Professora Alinne Veiga"
date: "2020-2"
output: 
 beamer_presentation: 
  fonttheme: professionalfonts
fontsize: 9pt
header-includes: \usepackage{graphicx} \usepackage{fancyhdr} \pagestyle{fancy}
 \fancyhf{}  \renewcommand{\headrulewidth}{0pt} \fancyheadoffset{1cm} 
 \setlength\headheight{27pt} 
 \fancyhead[L]{\includegraphics[width=12cm]{C:/Users/alinn/OneDrive/Documentos/Aulas2020/Amostragem/logo.png}{  \thepage}} 
---
  

Now, using suggested modifications: 
 
---
title: "EST052 - AMOSTRAGEM"
subtitle: Aula 27 - PPT
author: "Professora Alinne Veiga"
date: "2020-2"
output: 
 beamer_presentation: 
  fonttheme: professionalfonts
fontsize: 9pt
header-includes: \usepackage{graphicx} \usepackage{fancyhdr} \pagestyle{fancy}
 \fancyhf{}  \renewcommand{\headrulewidth}{0pt} \fancyheadoffset{1cm} 
 \setlength\headheight{40pt} 
 \fancyhead[L]{\includegraphics[width=12cm]{C:/Users/alinn/OneDrive/Documentos/Aulas2020/Amostragem/logo.png}{  \thepage}} 
---

I still get:
 Output created: Aula27.pdf
Warning message:
Package fancyhdr Warning: \headheight is too small (0.0pt): 
(fancyhdr)                Make it at least 35.49564pt, for example:
(fancyhdr)                \setlength{\headheight}{35.49564pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:
Package fancyhdr Warning: \headheight is too small (0.0pt): 
(fancyhdr)                Make it at least 35.49564pt, for example:
(fancyhdr)                \setlength{\headheight}{35.49564pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:
Package fancyhdr Warning: \headheight is too small (0.0pt): 
(fancyhdr)                Make it at least 35.49564pt, for example:
(fancyhdr)                \setlength{\headheight}{35.49564pt}.
(fancyhdr)                You might also make \topmargin smaller to compensate:
Package fancyhdr Warning: \headheight is too small (0.0pt): 
(fancyhdr)                Make it at least 35.49564pt, for example:
(fancyhdr)                \setlength{\headheight}{35.49 [... truncated]

 

What happened !? why  are the options not working? 
Thank you for your help!
Alinne

**Comment by pietvo** [comment]
`Beamer` thinks is has control over its headers, and isn't aware of `fancyhdr`. It changes `\headheight` after you have set it, therefore you still get the warnings.
This can be solved by adding the following line, after you have set `\headheight`, but before `\begin{document}`, so for example at the end of your header:

`\setbeamertemplate{headline}{\vspace{\headheight}}`
