### ISSUE TITLE
Bug when using images?

### ISSUE THREAD

**Issue by Ypot** [pietvo/fancyhdr#6]
Hi
I am new user of TeX, and fancyhdr is the first package I'am learning to use (sorry).

Just a doubt: it seems to be necessary to add, after `\begin{document}`:
```
\maketitle
\thispagestyle{fancy}
```

Is that correct? 
I am an orgmode user, and I would like to set all the fancyhdr package using just the preamble, but this doesn't seem to work IF USING AN IMAGE:
```
\documentclass[A4]{article}
\usepackage{graphicx}
\usepackage{fancyhdr}
\pagestyle{fancy}

\fancyhead[L]{\includegraphics[height=1.5cm]{eolian}}

\fancyhead[R]{OK RIGHT}

\title{}
\begin{document}
%%%\maketitle
%%%\thispagestyle{fancy}

Contents
\end{document}
```

NB: The same issue seems to appear in the p. 17 of the _Training slides, with examples (German) [German]_

**Comment by pietvo** [comment]
Basically you are right.


    \maketitle

Generates contents of the title page, which is part of the document, so it belongs after `\begin{document}`.

    \thispagestyle{fancy}

This changes the page style of the current page, which also only makes sense after `\begin{document}`. In the preamble there is no 'current page'.

However, there is a way around. Put this in the preamble, and although that code is written in the preamble, it is executed after `\begin{document|`

```
\AtBeginDocument{
  \maketitle
  \thispagestyle{fancy}
}
```

And, by the way, you also have to include something like

`\setlength{\headheight}{50pt}` (depending on the height of your image, see the log file).
