### ISSUE TITLE
Title number in page foot or header disappear while package titlesec is used

### ISSUE THREAD

**Issue by EnkiduGilgamesh** [pietvo/fancyhdr#9]
I did like below to set my page foot:

```latex
\fancypagestyle{notemark}{% 
    \fancyhf{}% clear all header and footer fields 
    \fancyfoot[LE,RO]{\Large\textbf{\thepage}}
    \fancyfoot[LO]{\textit{\leftmark}} % \leftmark
    \fancyfoot[RE]{\textit{\rightmark}} % \rightmark
    \renewcommand{\headrulewidth}{0pt}
    \renewcommand{\footrulewidth}{0.4pt}
}
```

Then I changed my title style through **titlesec** package,

```latex
\usepackage{titlesec}
```

Once the package is included, the number of the title in page foot disappears, whereas the title display as usual.

![1](https://user-images.githubusercontent.com/58500246/144051667-a6b9e19d-4ab2-45e5-8f94-7f598374fd1c.png)

Could this issue be fixed?

**Comment by pietvo** [comment]
Well, I don't see that. So there must be more that you are not telling. Maybe you change `\chaptermark`, `\sectionmark` or `\subsectionmark` to not include the number?

This documents works as expected:

```
\documentclass[twoside]{article}

\usepackage{fancyhdr}
\usepackage{titlesec}
\usepackage{lipsum}
\fancypagestyle{notemark}{% 
    \fancyhf{}% clear all header and footer fields 
    \fancyfoot[LE,RO]{\Large\textbf{\thepage}}
    \fancyfoot[LO]{\textit{\leftmark}} % \leftmark
    \fancyfoot[RE]{\textit{\rightmark}} % \rightmark
    \renewcommand{\headrulewidth}{0pt}
    \renewcommand{\footrulewidth}{0.4pt}
}
\pagestyle{notemark}
\begin{document}
\section{Section}

\lipsum

\subsection{Subsection}

\lipsum

\end{document}
```

**Comment by EnkiduGilgamesh** [comment]
I am very sorry that I make a very stupid mistake. I am doing a Chinese project with **ctex**, and the document class doesn't support your package perfectly, which I saw just now by chance. Or, maybe the **titlesec**...

Now, I have given up using the **titlesec** and changed to the title setup command defined by **ctex**. It works perfectly. 

I am grateful for your help!

**Comment by pietvo** [comment]
I would be interested to know more about this, to see if I can do something about it (as long as I don't have to read Chinese).
Could you email me an example to pieter@vanoostrum.org?

**Comment by pietvo** [comment]
Final comment: This was not a problem with `fancyhdr`, but an incompatibility between `tex` and `titles`, which also appears if you use `\pagestyle{headings}`
